services:
  app:
    build: .
    container_name: app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www # <-- use relative path to go up one folder
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend

  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8100:80"
    volumes:
      - ./backend:/var/www # <-- same here
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bike_ecommerce
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    networks:
      - backend

networks:
  backend:
    driver: bridge
